server:
  port: 8081
spring:
  application:
    name: mod-reading-room
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:db}
  sql:
    init:
      # to boot up application despite of any DB connection issues
      continue-on-error: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
  jackson:
    default-property-inclusion: non_empty
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  cloud:
    openfeign:
      okhttp:
        enabled: true
  mustache:
    check-template-location: false
logging:
  level:
    _org.springframework.web.servlet.HandlerMapping.Mappings: debug
folio:
  tenant:
    validation:
      enabled: false
  environment: ${ENV:folio}
  system-user:
    enabled: false
    password: ${SYSTEM_USER_PASSWORD:dummy} # This is not used but added to avoid DI errors from folio-spring-system-user
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,httptrace
      base-path: /admin
  #  endpoint:
  #    health:
  #      show-details: always
  #      show-components: always
  ###################################################
  # Disable all checks except for readiness
  ###################################################
  health:
    defaults:
      enabled: false
    readinessstate:
      enabled: true
debug: false
